# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bghost.proto\"\x07\n\x05\x45mpty\"<\n\x0b\x41PIResponse\x12\x17\n\x0fresponsemessage\x18\x01 \x01(\t\x12\x14\n\x0cresponsecode\x18\x02 \x01(\x05\"%\n\nAPIMessage\x12\x17\n\x0fresponsemessage\x18\x01 \x03(\t\"\x1a\n\x0b\x64iskRequest\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t\":\n\x11\x64\x65\x66initionRequest\x12\x12\n\nschemaname\x18\x01 \x01(\t\x12\x11\n\ttablename\x18\x02 \x01(\t\"@\n\nibdRequest\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t\x12\x12\n\nschemaname\x18\x02 \x01(\t\x12\x11\n\ttablename\x18\x03 \x01(\t\"H\n\x0cghostRequest\x12\x12\n\nschemaname\x18\x01 \x01(\t\x12\x11\n\ttablename\x18\x02 \x01(\t\x12\x11\n\tstatement\x18\x03 \x01(\t\"Q\n\x12interactiveRequest\x12\x12\n\nschemaname\x18\x01 \x01(\t\x12\x11\n\ttablename\x18\x02 \x01(\t\x12\x14\n\x0cghostcommand\x18\x03 \x01(\t2\xd0\x03\n\x05ghost\x12\'\n\tdiskcheck\x12\x0c.diskRequest\x1a\x0c.APIResponse\x12\x33\n\x0f\x63heckdefinition\x12\x12.definitionRequest\x1a\x0c.APIResponse\x12\x1f\n\x07\x63utover\x12\x06.Empty\x1a\x0c.APIResponse\x12$\n\x0cputpanicflag\x12\x06.Empty\x1a\x0c.APIResponse\x12\x1f\n\x07\x63leanup\x12\x06.Empty\x1a\x0c.APIResponse\x12%\n\x06\x64ryrun\x12\r.ghostRequest\x1a\x0c.APIResponse\x12\'\n\x07\x65xecute\x12\r.ghostRequest\x1a\x0b.APIMessage0\x01\x12+\n\x0c\x65xecuteNohup\x12\r.ghostRequest\x1a\x0c.APIResponse\x12\x30\n\x0binteractive\x12\x13.interactiveRequest\x1a\x0c.APIResponse\x12,\n\x08rowcount\x12\x12.definitionRequest\x1a\x0c.APIResponse\x12$\n\x07ibdsize\x12\x0b.ibdRequest\x1a\x0c.APIResponseb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=22,
)


_APIRESPONSE = _descriptor.Descriptor(
  name='APIResponse',
  full_name='APIResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responsemessage', full_name='APIResponse.responsemessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responsecode', full_name='APIResponse.responsecode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=84,
)


_APIMESSAGE = _descriptor.Descriptor(
  name='APIMessage',
  full_name='APIMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responsemessage', full_name='APIMessage.responsemessage', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=123,
)


_DISKREQUEST = _descriptor.Descriptor(
  name='diskRequest',
  full_name='diskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='diskRequest.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=151,
)


_DEFINITIONREQUEST = _descriptor.Descriptor(
  name='definitionRequest',
  full_name='definitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schemaname', full_name='definitionRequest.schemaname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tablename', full_name='definitionRequest.tablename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=211,
)


_IBDREQUEST = _descriptor.Descriptor(
  name='ibdRequest',
  full_name='ibdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='ibdRequest.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schemaname', full_name='ibdRequest.schemaname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tablename', full_name='ibdRequest.tablename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=277,
)


_GHOSTREQUEST = _descriptor.Descriptor(
  name='ghostRequest',
  full_name='ghostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schemaname', full_name='ghostRequest.schemaname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tablename', full_name='ghostRequest.tablename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statement', full_name='ghostRequest.statement', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=351,
)


_INTERACTIVEREQUEST = _descriptor.Descriptor(
  name='interactiveRequest',
  full_name='interactiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schemaname', full_name='interactiveRequest.schemaname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tablename', full_name='interactiveRequest.tablename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ghostcommand', full_name='interactiveRequest.ghostcommand', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=434,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['APIResponse'] = _APIRESPONSE
DESCRIPTOR.message_types_by_name['APIMessage'] = _APIMESSAGE
DESCRIPTOR.message_types_by_name['diskRequest'] = _DISKREQUEST
DESCRIPTOR.message_types_by_name['definitionRequest'] = _DEFINITIONREQUEST
DESCRIPTOR.message_types_by_name['ibdRequest'] = _IBDREQUEST
DESCRIPTOR.message_types_by_name['ghostRequest'] = _GHOSTREQUEST
DESCRIPTOR.message_types_by_name['interactiveRequest'] = _INTERACTIVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

APIResponse = _reflection.GeneratedProtocolMessageType('APIResponse', (_message.Message,), {
  'DESCRIPTOR' : _APIRESPONSE,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:APIResponse)
  })
_sym_db.RegisterMessage(APIResponse)

APIMessage = _reflection.GeneratedProtocolMessageType('APIMessage', (_message.Message,), {
  'DESCRIPTOR' : _APIMESSAGE,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:APIMessage)
  })
_sym_db.RegisterMessage(APIMessage)

diskRequest = _reflection.GeneratedProtocolMessageType('diskRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISKREQUEST,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:diskRequest)
  })
_sym_db.RegisterMessage(diskRequest)

definitionRequest = _reflection.GeneratedProtocolMessageType('definitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEFINITIONREQUEST,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:definitionRequest)
  })
_sym_db.RegisterMessage(definitionRequest)

ibdRequest = _reflection.GeneratedProtocolMessageType('ibdRequest', (_message.Message,), {
  'DESCRIPTOR' : _IBDREQUEST,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:ibdRequest)
  })
_sym_db.RegisterMessage(ibdRequest)

ghostRequest = _reflection.GeneratedProtocolMessageType('ghostRequest', (_message.Message,), {
  'DESCRIPTOR' : _GHOSTREQUEST,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:ghostRequest)
  })
_sym_db.RegisterMessage(ghostRequest)

interactiveRequest = _reflection.GeneratedProtocolMessageType('interactiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTERACTIVEREQUEST,
  '__module__' : 'ghost_pb2'
  # @@protoc_insertion_point(class_scope:interactiveRequest)
  })
_sym_db.RegisterMessage(interactiveRequest)



_GHOST = _descriptor.ServiceDescriptor(
  name='ghost',
  full_name='ghost',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=437,
  serialized_end=901,
  methods=[
  _descriptor.MethodDescriptor(
    name='diskcheck',
    full_name='ghost.diskcheck',
    index=0,
    containing_service=None,
    input_type=_DISKREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checkdefinition',
    full_name='ghost.checkdefinition',
    index=1,
    containing_service=None,
    input_type=_DEFINITIONREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='cutover',
    full_name='ghost.cutover',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putpanicflag',
    full_name='ghost.putpanicflag',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='cleanup',
    full_name='ghost.cleanup',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='dryrun',
    full_name='ghost.dryrun',
    index=5,
    containing_service=None,
    input_type=_GHOSTREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='execute',
    full_name='ghost.execute',
    index=6,
    containing_service=None,
    input_type=_GHOSTREQUEST,
    output_type=_APIMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='executeNohup',
    full_name='ghost.executeNohup',
    index=7,
    containing_service=None,
    input_type=_GHOSTREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='interactive',
    full_name='ghost.interactive',
    index=8,
    containing_service=None,
    input_type=_INTERACTIVEREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rowcount',
    full_name='ghost.rowcount',
    index=9,
    containing_service=None,
    input_type=_DEFINITIONREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ibdsize',
    full_name='ghost.ibdsize',
    index=10,
    containing_service=None,
    input_type=_IBDREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GHOST)

DESCRIPTOR.services_by_name['ghost'] = _GHOST

# @@protoc_insertion_point(module_scope)
